In [3]:
import pandas as pd 
import numpy as np
from sklearn.metrics import confusion_matrix, classification_report

In [11]:
score_threshold_col=['Original','is_0.1score','is_0.2score','is_0.3score','is_0.4score','is_0.5score','is_0.6score','is_0.7score']

In [6]:
# File_Path는 분류된 파일의 경로를 입력
file_path_soar=r"C:\python\practice\Alert\0728~\Data\result_labeled_df_soaring.xlsx"
scoring_soaring=pd.read_excel(file_path_soar, header=0)
soar_scoring_matrix=scoring_soaring.iloc[:,4:13] # 실제 파일 구조 확인해서 몇 열까지 살릴지 고민해야함

In [7]:
soar_scoring_matrix

,Original,is_0.1score,is_0.2score,is_0.3score,is_0.4score,is_0.5score,is_0.6score,is_0.7score,AI_Label
0,1,1,1,1,1,0,0,0,1
1,1,1,1,1,1,1,1,0,1
2,1,1,1,1,1,0,0,0,0
3,1,1,1,1,1,1,1,1,0
4,1,1,1,1,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...
695,1,1,1,1,1,1,0,0,0
696,1,1,1,1,1,1,0,0,0
697,1,1,1,1,1,1,0,0,0
698,1,1,1,1,1,1,0,0,0
699,1,1,1,1,1,1,0,0,0

In [ ]:
scoring_neg=pd.read_excel(file_path_soar, header=0)

In [8]:

soar_scoring_matrix

,Original,is_0.1score,is_0.2score,is_0.3score,is_0.4score,is_0.5score,is_0.6score,is_0.7score,AI_Label
0,1,1,1,1,1,0,0,0,1
1,1,1,1,1,1,1,1,0,1
2,1,1,1,1,1,0,0,0,0
3,1,1,1,1,1,1,1,1,0
4,1,1,1,1,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...
695,1,1,1,1,1,1,0,0,0
696,1,1,1,1,1,1,0,0,0
697,1,1,1,1,1,1,0,0,0
698,1,1,1,1,1,1,0,0,0
699,1,1,1,1,1,1,0,0,0

In [9]:
# Confusion_matrix 반환하는 함수
y_true = soar_scoring_matrix['AI_Label'].astype(int)
confusion_matrix_dict = {}

def matrix_extractor(df):
    for y_pred_col in score_threshold_col:
        # 해당 임계점의 예측값 가져오기
        y_pred = df[y_pred_col].astype(int)
        
        # 혼동행렬 계산
        cm = confusion_matrix(y_true, y_pred)
        tn, fp, fn, tp = cm.ravel()
        
        # 딕셔너리에 저장! (이름을 confusion_matrix_dict로 정확히 맞춤)
        confusion_matrix_dict[y_pred_col] = [tn, fp, fn, tp]
    cm_df_soar = pd.DataFrame(confusion_matrix_dict, index=['TN(정답)', 'FP(오탐)', 'FN(미탐)', 'TP(정답)'])
    return cm_df_soar

In [12]:
soar_matrix=matrix_extractor(soar_scoring_matrix)

In [13]:
soar_matrix

,Original,is_0.1score,is_0.2score,is_0.3score,is_0.4score,is_0.5score,is_0.6score,is_0.7score
TN(정답),0,0,0,1,2,238,326,356
FP(오탐),397,397,397,396,395,159,71,41
FN(미탐),0,0,0,6,6,214,285,295
TP(정답),303,303,303,297,297,89,18,8

In [14]:
soar_matrix.to_excel('soar_cm.xlsx',header=True)

In [22]:
neg_scoring_matrix

     is_0.4score  is_0.5score  is_0.6score  is_0.7score
0              1            1            0            0
1              1            1            1            0
2              1            1            0            0
3              1            1            0            0
4              1            1            0            0
..           ...          ...          ...          ...
775            1            0            0            0
776            1            0            0            0
777            1            1            0            0
778            0            0            0            0
779            1            0            0            0

[780 rows x 4 columns]

In [32]:
# Confusion_matrix 반환하는 함수
y_true = neg_scoring_matrix['AI_Label'].astype(int)
confusion_matrix_dict = {}

def matrix_extractor(df):
    for y_pred_col in score_threshold_col:
        # 해당 임계점의 예측값 가져오기
        y_pred = df[y_pred_col].astype(int)
        
        # 혼동행렬 계산
        cm = confusion_matrix(y_true, y_pred)
        tn, fp, fn, tp = cm.ravel()
        
        # 딕셔너리에 저장! (이름을 confusion_matrix_dict로 정확히 맞춤)
        confusion_matrix_dict[y_pred_col] = [tn, fp, fn, tp]
    cm_df_neg = pd.DataFrame(confusion_matrix_dict, index=['TN(정답)', 'FP(오탐)', 'FN(미탐)', 'TP(정답)'])
    return cm_df_neg

In [36]:
neg_matrix=matrix_extractor(neg_scoring_matrix)

In [37]:
neg_matrix.to_excel('neg_cm.xlsx',header=True)